### ISSUE TITLE
Safari 8 Crash after AUTH accept

### ISSUE THREAD

**Issue by 5HT** [TrueLink/TrueLink#1]

**Comment by wizzard0** [comment]
Confirmed on Yosemite and Safari 8, probably crash when playing sound or trying to show desktop notification. So much for HTML5!

**Comment by wizzard0** [comment]
Should be fixed in 15.01.28-087bda2c5f7e+

**Comment by wizzard0** [comment]
Confirmed as working in 15.01.28-087bda2c5f7e+
